fixes

diff --git a/daily_mfu_get b/daily_mfu_get
--- a/daily_mfu_get
+++ b/daily_mfu_get
@@ -10,28 +10,30 @@ echo $(date) > LOGS/log.mfu-get-funds 2>&1
 #echo $PATH >> LOGS/log.mfu-get-funds 2>&1
 source ~/.bash_profile
 #echo $PATH >> LOGS/log.mfu-get-funds 2>&1
-which python3
+conda activate scraping
+which python
+#pip freeze | grep yfin
 
-sleep 10
+sleep 5
 
 echo $(date) "-------- starting crypto"
-python3 scrape/crypto-get-funds.py >> LOGS/log.mfu-get-funds 2>&1
+python scrape/crypto-get-funds.py >> LOGS/log.mfu-get-funds 2>&1
 STAT1=$?
 echo "######## crypto_get_funds returned " $STAT1 "\n" | tee -a LOGS/log.mfu-get-funds 2>&1
 if [[ $STAT1 == 1 ]]; then 
 	echo "######## crypto FAILED, need to FIX!!!!!!!! ********\n" >> LOGS/log.mfu-get-funds 2>&1
 fi
 
-echo $(date) "-------- starting axis"
-python3 scrape/axis-get-funds.py >> LOGS/log.mfu-get-funds 2>&1
-STAT2=$?
-echo "######## axis_get_funds returned " $STAT2 "\n" | tee -a LOGS/log.mfu-get-funds 2>&1
-if [[ $STAT2 == 1 ]]; then 
-	echo "######## axis FAILED, need to FIX!!!!!!!! ********\n" >> LOGS/log.mfu-get-funds 2>&1
-fi
+# echo $(date) "-------- starting axis"
+# python scrape/axis-get-funds.py >> LOGS/log.mfu-get-funds 2>&1
+# STAT2=$?
+# echo "######## axis_get_funds returned " $STAT2 "\n" | tee -a LOGS/log.mfu-get-funds 2>&1
+# if [[ $STAT2 == 1 ]]; then 
+# 	echo "######## axis FAILED, need to FIX!!!!!!!! ********\n" >> LOGS/log.mfu-get-funds 2>&1
+# fi
 
 echo $(date) "-------- starting gold"
-python3 scrape/gold-get-rate.py >> LOGS/log.mfu-get-funds 2>&1
+python scrape/gold-get-rate.py >> LOGS/log.mfu-get-funds 2>&1
 STAT3=$?
 echo "######## gold_get_rate returned " $STAT3 "\n" | tee -a LOGS/log.mfu-get-funds 2>&1
 if [[ $STAT3 == 1 ]]; then 
@@ -39,23 +41,23 @@ if [[ $STAT3 == 1 ]]; then
 fi
 
 echo $(date) "-------- starting casparse"
-python3 scrape/casparse-analyze.py >> LOGS/log.mfu-get-funds 2>&1
+python scrape/casparse-analyze.py >> LOGS/log.mfu-get-funds 2>&1
 STAT4=$?
 echo "######## casparse-analyze returned " $STAT4 "\n" | tee -a  LOGS/log.mfu-get-funds 2>&1
 if [[ $STAT4 == 1 ]]; then 
 	echo "######## casparse-analyze FAILED, need to FIX!!!!!!!! ********\n" >> LOGS/log.mfu-get-funds 2>&1
 fi
 
-echo $(date) "-------- starting hdfc"
-python3 scrape/hdfc-get-funds.py >> LOGS/log.mfu-get-funds 2>&1
-STAT5=$?
-echo "######## hdfc_get_funds returned " $STAT5 "\n" | tee -a LOGS/log.mfu-get-funds 2>&1
-if [[ $STAT5 == 1 ]]; then 
-	echo "######## hdfc FAILED, need to FIX!!!!!!!! ********\n" >> LOGS/log.mfu-get-funds 2>&1
-fi
+# echo $(date) "-------- starting hdfc"
+# python scrape/hdfc-get-funds.py >> LOGS/log.mfu-get-funds 2>&1
+# STAT5=$?
+# echo "######## hdfc_get_funds returned " $STAT5 "\n" | tee -a LOGS/log.mfu-get-funds 2>&1
+# if [[ $STAT5 == 1 ]]; then 
+# 	echo "######## hdfc FAILED, need to FIX!!!!!!!! ********\n" >> LOGS/log.mfu-get-funds 2>&1
+# fi
 
 echo $(date) "-------- starting cm"
-python3 scrape/cm-get-funds.py >> LOGS/log.mfu-get-funds 2>&1
+python scrape/cm-get-funds.py >> LOGS/log.mfu-get-funds 2>&1
 STAT6=$?
 echo "######## cm_get_funds returned " $STAT6 "\n" | tee -a LOGS/log.mfu-get-funds 2>&1
 if [[ $STAT6 == 1 ]]; then 
@@ -63,7 +65,7 @@ if [[ $STAT6 == 1 ]]; then
 fi
 
 echo $(date) "-------- starting stocks"
-python3 scrape/stocks-get-funds.py >> LOGS/log.mfu-get-funds 2>&1
+python scrape/stocks-get-funds.py >> LOGS/log.mfu-get-funds 2>&1
 STAT7=$?
 echo "######## stocks_get_funds returned " $STAT7 "\n" | tee -a LOGS/log.mfu-get-funds 2>&1
 if [[ $STAT7 == 1 ]]; then 
@@ -71,7 +73,7 @@ if [[ $STAT7 == 1 ]]; then
 fi
 
 echo $(date) "-------- starting vested"
-python3 scrape/vested-get-funds.py >> LOGS/log.mfu-get-funds 2>&1
+python scrape/vested-get-funds.py >> LOGS/log.mfu-get-funds 2>&1
 STAT8=$?
 echo "######## vested_get_funds returned " $STAT8 "\n" | tee -a LOGS/log.mfu-get-funds 2>&1
 if [[ $STAT8 == 1 ]]; then 
@@ -107,7 +109,7 @@ fi
 
 echo $(date) "-------- starting report"
 SUBJECT="FAILURE"
-python3 analyze/generate-report.py >> LOGS/log.generate-report 2>&1
+python analyze/generate-report.py >> LOGS/log.generate-report 2>&1
 STATREP=$?
 echo "######## generate-report returned " $STATREP "\n" >> LOGS/log.generate-report 2>&1
 if [[ $STATREP == 0 ]]; then SUBJECT="SUCCESS"; fi;
@@ -121,7 +123,7 @@ echo "##############################################\n" >> LOGS/log.mfu-get-fund
 cat LOGS/log.generate-report LOGS/log.mfu-get-funds > LOGS/log.email 
 
 echo $(date) "-------- starting email"
-python3 analyze/send_mail.py -s "$EMAILSUB" -f LOGS/log.email
+python analyze/send_mail.py -s "$EMAILSUB" -f LOGS/log.email
 cat LOGS/log.email >> LOGS/clog.mfu-get-funds
 
 echo $(date) "-------- finished daily_mfu_get"
